- webxr-api/device.rs
- webxr-api/lib.rs
- webxr-api/registry.rs
- webxr-api/session.rs
- webxr-api/webgl.rs
Some changes to the API for compatibility with Servo:
* Add a device registry API
* Make the WebGL external images API compatible with Servo's `WebGLMsgSender`
* Bind the images API after creation, since this is what WebXR does
* Remove `GLFactory` since Servo doesn't have one of those, it has a `GLContextFactory` which builds a context, not just binds the GL API
> An API which Servo can implement

- webxr-api/device.rs
- webxr-api/lib.rs
- webxr-api/registry.rs
- webxr-api/session.rs
Run the XR registry on the main thread, which allows devices which have main-thread affinity to be implemented without using `Send`.
> Support devices which have main thread affinity

- .travis.yml
- webxr-api/device.rs
- webxr/glwindow/mod.rs
- webxr/lib.rs
Port the glwindow test device from rust-webvr to webxr
>  Add glwindow test WebXR device 

- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/registry.rs
- webxr/Cargo.toml
- webxr/headless/mod.rs
- webxr/lib.rs
This PR adds a frist-cut API for mocking, and a headless implementation. It's based on the webxr-test API (https://github.com/immersive-web/webxr-test-api/) and the rust-webvr mock API (https://github.com/servo/rust-webvr/blob/master/rust-webvr-api/src/mock.rs).
> Add support for mock XR devices

- webxr/headless/mod.rs
Apparently you get GL errors if you create a sync object but never fence on it.
> The headless test device shouldn't ignore the sync object

- webxr/Cargo.toml
- webxr/glwindow/mod.rs
Some bugfixes for the glwindow test device. The most exciting one is it's now got a trait for the window, which means we can run it in headless mode in servo.
> Various bugfixes for the glwindow test device

- webxr-api/device.rs
- webxr-api/lib.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
Devices can provide their recommended resolution (by default, large enough to hold all the viewports).
>  Devices provide a recommended device resolution 

- webxr-api/device.rs
- webxr-api/events.rs
- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
- webxr/headless/mod.rs
Allow the device to send events back to script
r? @asajeffrey
> Add event support, use for disconnection and inputs

- webxr-api/lib.rs
- webxr-api/registry.rs
- webxr-api/session.rs
This PR adds a callback which can be called from any process to wake up the main thead. It's needed because of servo embeddings like glutin, where the main thread can be blocked waiting for UI events, and not listening for events from servo.
> Add a main thread waker

- webxr-api/device.rs
- webxr-api/lib.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
- webxr/headless/mod.rs
> Fix mocking and session ending event loop models

- webxr-api/lib.rs
- webxr-api/session.rs
- webxr-api/webgl.rs
Have sessions track which texture WebGL is drawing into. This is the webxr part of fixing a bug where XR was using the default canvas framebuffer rather than the XR framebuffer.
> XR Sessions track which texture to draw to

- webxr-api/device.rs
- webxr-api/webgl.rs
- webxr/glwindow/mod.rs
- webxr/headless/mod.rs
If a webxr device and webgl are both running on the same thread, then there's no need for a GLsync object.
> Make GLsync object optional

- webxr-api/Cargo.toml
- webxr-api/device.rs
- webxr-api/registry.rs
- webxr/Cargo.toml
- webxr/build.rs
- webxr/egl.rs
- webxr/gles.rs
- webxr/googlevr/device.rs
- webxr/googlevr/discovery.rs
- webxr/googlevr/input.rs
- webxr/lib.rs
- webxr/magicleap/magicleap_c_api.h
- webxr/magicleap/magicleap_c_api.rs
- webxr/magicleap/mod.rs
This PR ports over the magicleap back end from rust-webvr.
I also did a few drive-by fixes, none of which are very exciting.
> Add a Magic Leap back end

- .travis.yml
- webxr-api/view.rs
- webxr/Cargo.toml
- webxr/googlevr/device.rs
- webxr/lib.rs
- webxr/openxr/mod.rs
This enters immersive mode without erroring, however doesn't yet render anything. I'm waiting for @paulrouget to write the code that blits the two subregions of the supplied openGL/angle texture into the swapchain-supplied D3D surfaces.
To work properly this needs the `hl` branch on servo/openxrs, and also the DLL built by https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/master/loader/openxr_loader_uwp.vcxproj (renamed to `openxr_loader.dll`)
r? @jdm
> OpenXR backend

- webxr/Cargo.toml
Tested and works. Once this lands Hololens webxr builds don't need to patch any dependencies.
r? @asajeffrey or @jdm
> Bump openxr dependency

- webxr/openxr/mod.rs
This is inefficient, but it works.
We should figure out ANGLE sharing to do a direct blit, next.
r? @jdm
> Copy pixels to d3d texture in openxr backend

- webxr-api/device.rs
- webxr-api/frame.rs
- webxr-api/lib.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/lib.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
- webxr/utils.rs
r? @asajeffrey
I couldn't handle magicleap, sadly, since I can't get it to build, and it seems to manage its own projection matrices
Fixes #32
> Allow setting near/far planes and listening for view update events

- webxr/openxr/mod.rs
This allows testing out a bunch of existing three.js content in AR headsets.
> Allow immersive VR sessions in OpenXR backend

- webxr-api/session.rs
- webxr/openxr/mod.rs
This will end the openxr session (back to 2D view in the case of HoloLens).
It's still missing the call to `session.end()` (see #47).
Fix #48
> request openxr shutdown on quit

- webxr-api/device.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
OpenXR shuts down asynchronously.
Ideally webxr would intercept the `SessionEnd` event. But for now, I think this will do.
> Asynchonous shutdown

- webxr-api/device.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
This fixes 2 different crashes at shutdown.
The initial approach of checking if session was running, then call RAF would fail as we would call `is_running()` before processing the event.
I got rid of the `is_running()` mechanic and instead made `wait_for_animation_frame` return an Option. Assuming that returning None mean the session has ended.
Fix #47
> More shutdown event processing

- webxr/openxr/mod.rs
This is the [recommended format](https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/master/README.md#select-a-pixel-format), and it looks like it changed recently.
We should eventually add some negotiation (think a list of preferred formats and the associated gl formats) but that doesn't have to be done now.
fixes https://github.com/servo/webxr/issues/54
r? @paul @jdm
> Change default fxgi format

- webxr/openxr/mod.rs
Requires https://github.com/servo/webxr/pull/65
This treats the right hand as an input source. While I've tested the input code, I haven't yet tested this hooked up to the Servo DOM (https://github.com/servo/servo/pull/24362), so I'd like to hold off on merging this until I get a chance
Still, feel free to review the last few commits that have "openxr" in their bodies
> Input support for OpenXR

- webxr/openxr/mod.rs
Fixes https://github.com/servo/webxr/issues/68
These are the only two formats that I've seen get requested, as the warning shows further ones we should add support
r? @jdm
> Be more flexible in picking formats

- webxr-api/input.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
Servo PR incoming, can land independently
r? @jdm @asajeffrey
> openxr: support left hands and grips

- webxr/openxr/mod.rs
Tested on hololens, works.
The hololens exposes a VIEW space which we can use to calculate viewer poses, instead of LERPing the eyes. This shouldn't have any visible behavioral differences.
It's not clear to me if this is faster, since now we query poses twice in the render loop; we still need the LOCAL poses to compute the projection views. We may be able to use VIEW poses there instead, i'm not sure. It's not clear to me _why_ openxr needs this information.
Draft PR because it doesn't yet compile against master due to surfman issues, and i need to do some cleanups.
> Stop LERPing views

- webxr/openxr/mod.rs
STOPPING is the transition into the IDLE state, not an exit event
Ideally we should be using this for triggering visibility blurred events, but I'm never seeing the IDLE or VISIBLE states.
I suspect this has something to do with wait_for_animation_frame, HL may be pausing w_a_f when it goes into IDLE, and throwing away the events we don't immediately ask for.
I suspect those events are going into EventsLost, whch we don't yet check.
r? @jdm
> Remove STOPPING state handling

- webxr/openxr/mod.rs
We were submitting the wrong pose values for the right eye, leading to the reprojection being distorted and causing #80
Fixes #80
> openxr: Submit correct pose values for reprojection

- webxr-api/Cargo.toml
- webxr-api/device.rs
- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/registry.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/googlevr/discovery.rs
- webxr/headless/mod.rs
- webxr/lib.rs
- webxr/openxr/mod.rs
Means that changes to surfman don't cause rebuilds of anything that depends on webxr-api.
> Remove dependency from webxr-api to surfman

- webxr-api/events.rs
- webxr-api/input.rs
- webxr-api/lib.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
We can't yet support squeeze events on hololens, but the code here will make it super easy to add support when we need to.
r? @jdm
This is a breaking change and needs to be landed simultaneously with https://github.com/servo/servo/pull/24838
> Prepare API for squeeze events

- webxr-api/device.rs
- webxr-api/session.rs
- webxr-api/view.rs
- webxr/headless/mod.rs
For inline sessions the client should be doing all the calculations.
servo side: https://github.com/servo/servo/pull/25144
> Add Views::Inline

- webxr/headless/mod.rs
Otherwise we very rapidly tick frames, flooding the event loop
r? @asajeffrey
> Add frame delay in headless test

- webxr/headless/mod.rs
> Move mock disconnected check to supports_session

- webxr-api/frame.rs
- webxr-api/lib.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
> Send epoch timestamp with the frame

- webxr-api/registry.rs
- webxr-api/session.rs
This does not make the render loop _completely_ independent of script: it still waits for script to submit a frame. If we don't, frames will be dropped (and I'm not sure what strategy to use there).
I'm going to test this soon and see if it actually improves our framerate.
Servo side: https://github.com/servo/servo/pull/25343
r? @jdm
> Do not wait for rAF to be requested

- webxr-api/mock.rs
- webxr/headless/mod.rs
Needed for input mocking. I'm working on the actual servo-side input mocking stuff as well as hit test mocking, but I thought I'd land this first.
r? @asajeffrey or @jdm
> Expose TriggerSelect, properly handle input removal/adding

- webxr-api/device.rs
- webxr-api/error.rs
- webxr-api/events.rs
- webxr-api/input.rs
- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/registry.rs
- webxr-api/session.rs
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/googlevr/discovery.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
r? @jdm @asajeffrey
Servo side: https://github.com/servo/servo/pull/25504
> Support for features, profiles, and mocking ray mode/handedness

- webxr/openxr/mod.rs
The Y axis is up.
We should use actual stage spaces for this, but for now I'll set this to a value that is approximately correct.
r? @jdm
> Correct floor-level

- webxr-api/lib.rs
- webxr-api/registry.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/openxr/mod.rs
Depends on:
* https://github.com/servo/surfman/pull/151
* https://github.com/asajeffrey/surfman-chains/pull/7
> Avoid extra blit for GL->D3D.

- webxr/headless/mod.rs
We really want to stop using the main thread code path as much as possible, and it avoids timeouts in https://github.com/servo/servo/pull/25837/ when the main thread blocks in other parts of the pipeline and never ends up processing the pending XR events.
> Run headless device on its own thread.

- .travis.yml
rustfmt has been missing from nightlies for three days (https://rust-lang.github.io/rustup-components-history/) and this is preventing us from merging anything in repositories that require it.
> Disable nightly while rustfmt is missing.

- webxr/openxr/input.rs
- webxr/openxr/mod.rs
Hololens continues to use simple_controller until we can start using [`XR_MSFT_hand_interaction_preview`](https://microsoft.github.io/OpenXR-MixedReality/openxr_preview/specs/openxr.html#XR_MSFT_hand_interaction_preview) (blocked on https://github.com/Ralith/openxrs/issues/17 , and installing a preview runtime on the device). This puts the framework in place for supporting that easily.
To test, check out the threejs paint demo; holding the squeeze button and moving your hand vertically should change the paintbrush size.
> Support squeeze events for WinMR controllers

- webxr/openxr/input.rs
- webxr/openxr/mod.rs
This adds a gesture (currently: "palm facing upwards") to open up a context menu.
servo side: https://github.com/servo/servo/pull/26051
r? @jdm
> Add a gesture to open up a context menu; fix quitting

- webxr/openxr/input.rs
- webxr/openxr/mod.rs
This changes the context menu gesture to be "looking straight at palm, with palm facing you" (easiest way to do this is hold the palm straight up in front of your face), which was suggested by Alex earlier. It also triggers the cancel events correctly so that when the context menu is exited the application doesn't think there was a continuous select event while the menu was shown.
This may make less sense for WinMR devices, but I can add a direct menu button press for those.
r? @jdm
> Improve context menu gesture to incorporate gaze, correctly trigger selectcancel events when the context menu is shown

- webxr/jni_utils.rs
Removes a build warning caused by `mem::uninitialized()` being deprecated.
> Remove build warning

- webxr-api/device.rs
- webxr-api/frame.rs
- webxr-api/hittest.rs
- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/session.rs
- webxr-api/space.rs
- webxr-api/util.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/mod.rs
Servo side: https://github.com/servo/servo/pull/26171
This adds support for all non-transient parts of he [WebXR Hit Test Module](https://immersive-web.github.io/hit-test), including mocking support.
This has not yet been hooked up to script and is thus completely untested.
r? @jdm
> Implement support for hit testing, use in mock backend

- webxr/Cargo.toml
It’s unused since https://github.com/servo/webxr/pull/143
> Remove glutin dependency

- webxr/glwindow/mod.rs
This doesn't change much by itself, but means we can use more interesting shaders later on.
> Replace the use of glBlitFramebuffer in glwindow by a shader

- webxr-api/hand.rs
- webxr-api/input.rs
- webxr-api/lib.rs
- webxr-api/space.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
This doesn't actually add support in openxr, just getting the API out early for review.
> Add hands to API

- webxr/glwindow/mod.rs
The first time using glwindow to render 3D content, unsurprisingly kicked up some issues.
> Add a anaglyphic red-cyan rendering mode to glwindow

- webxr-api/space.rs
- webxr/glwindow/mod.rs
Fixes a panic on macos (https://github.com/servo/servo/issues/26340) and puts back blit mode, since for some reason the shaders don't render on macos.
> Workarounds for glwindow on macos

- webxr-api/device.rs
- webxr-api/frame.rs
- webxr-api/lib.rs
- webxr-api/session.rs
- webxr-api/view.rs
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/headless/mod.rs
- webxr/magicleap/mod.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
Fixes https://github.com/servo/webxr/issues/173
This contains many related changes:
- Makes the views state per-frame
- Makes viewports no longer part of the views state, and only occasionally updated
- Switches view transforms to being native-relative (and related cleanups in openxr, reducing the number of `locate_views` calls)
- Caching of projection matrices in openxr
- Cleanups of the headless backend to support multiple sessions on the same device (only relevant for inline)
Overall this should improve stability with a _tiny_ performance win from not doing as much space-locating each frame.
servo side: https://github.com/servo/servo/pull/26551
> Send eye positions per-view, relative to the native space

- webxr-api/Cargo.toml
- webxr-api/device.rs
- webxr-api/error.rs
- webxr-api/frame.rs
- webxr-api/layer.rs
- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr-api/registry.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/googlevr/device.rs
- webxr/googlevr/discovery.rs
- webxr/headless/mod.rs
- webxr/lib.rs
- webxr/openxr/mod.rs
- webxr/surfman_layer_manager.rs
This PR adds layer management to webxr. There's an API for creating and destroying layers, and for specifying which layers to use in a frame. This removes all of the special-cased code for openxr, since the layer manager can be run in the webgl thread.
> Added API for layer management

- webxr/openxr/mod.rs
Fix issues with secondary views and layer management.
> Fix issues with secondary views and layer management.

- webxr-api/layer.rs
- webxr/openxr/mod.rs
- webxr/surfman_layer_manager.rs
Creating a depth/stencil attachment requires access to the GL bindings when creating/destroying a layer, so the layer managemnt API has to change slightly.
> Support depth and stencil in surfman layer manager

- webxr/openxr/mod.rs
This fixes the browser locking up when calling `session.end()`, and also fixes #156.
> Clean up when ending XR sessions

- webxr/gl_utils.rs
- webxr/lib.rs
- webxr/openxr/mod.rs
- webxr/surfman_layer_manager.rs
This fixes a regression where previously servo was getting surfmn-chains to clear the webxr render target, but that's not really appropriate now we have a layer manager.
> Clear textures on each begin frame

- webxr-api/session.rs
- webxr/openxr/mod.rs
Implements https://github.com/immersive-web/webxr/pull/1083 , and moves the constant to a pref to be toggled by the user.
For now I'd like to keep it a pref since there are perf implications of always enabling this.
> Allow support for secondary views to be toggled by a pref

- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/surfman_layer_manager.rs
Depends on https://github.com/asajeffrey/surfman-chains/pull/9.
> Adjust for surfman-chains swapping changes.

- webxr/glwindow/mod.rs
This change gets AR examples, and multi-layer examples from WebXR Layers to work.
> Enable alpha blending in the glwindow device

- webxr/Cargo.toml
To complete the update of winit used by Servo (servo/servo#29382), a new version 0.6.0 of surfman has been published to crates.io (servo/surfman#249). To address compilation errors in Servo about mismatched types due to duplicated versions of surfman, we will need to update all references in Servo to the same version (0.6.0).
> Update surfman to 0.6

- webxr-api/Cargo.toml
- webxr/Cargo.toml
ipc-channel used in servo needs to bumped to 0.16.1 to complete servo/servo#29467, but that requires the same version to be used by webxr crates as well.
> Update to ipc-channel v0.16 & crossbeam-channel v0.5

- webxr-api/util.rs
As discovered during my [experimentation](https://twitter.com/msub2official/status/1677879727556624384) the projection matrix was being constructed in row-major order, but [WebXR expects it to be column-major](https://www.w3.org/TR/webxr/#matrices).
> Row-major -> Column-major on projection matrix

- webxr/Cargo.toml
This allows us to remove the winit dependency.
> Upgrade surfman to 0.9.0

- webxr/gl_utils.rs
- webxr/openxr/mod.rs
- webxr/surfman_layer_manager.rs
Fixes #216. This allows for proper rendering with the Oculus/Quest Link runtime by swapping up/down angles before setting views and reversing winding order, as it does not allow for swapping fov angles during composition layer submission.
Worth noting this will need adjustment if this code ever stops assuming that sessions are using D3D11, especially for future Linux support.
> Support OpenXR runtimes that do not support fovMutable

- .github/workflows/rust.yml
- webxr-api/Cargo.toml
- webxr-api/frame.rs
- webxr-api/session.rs
- webxr/Cargo.toml
- webxr/glwindow/mod.rs
- webxr/headless/mod.rs
- webxr/openxr/mod.rs
A very ancient version of `time` was used with security vulnerabilities.
Remove all uses of time including the `profile` feature. Hopefully in
the future, some of this functionality can be restored, but in the
meantime get Servo closer to no longer using old `time`.
> Remove use of `time`

- webxr/Cargo.toml
- webxr/openxr/input.rs
- webxr/openxr/interaction_profiles.rs
- webxr/openxr/mod.rs
This introduces support for a wider range of OpenXR interaction profiles and properly handles updating the associated XRInputSource when the active interaction profile changes.
> Surface supported interaction profiles from OpenXR runtime

- webxr/openxr/mod.rs
Same change as #111 but rebased on the current version of the codebase.
> Use recommended swapchain sample count for OpenXR

- webxr-api/events.rs
- webxr-api/input.rs
- webxr/headless/mod.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
This extends the current input handling in the OpenXR backend to expose button and axis inputs for use with the WebXR gamepads module. It will require an update in Servo as well to handle the new event for changed input.
> OpenXR: Expose button/axis inputs for WebXR gamepads

- webxr/openxr/input.rs
- webxr/openxr/interaction_profiles.rs
This expands the handling for hand tracking in OpenXR to be able to better get both aim pose and select status from hand trackers, as previously it was relying on hardcoded actions that don't exist in every runtime. This should supersede #151 as well
> OpenXR: Add interaction profiles for hand tracking

- webxr-api/device.rs
- webxr-api/session.rs
- webxr/openxr/mod.rs
This PR surfaces framerate info from the OpenXR runtime, which in turn helps support some of the newer features on XRSession like `XRSession.frameRate`, `XRSession.supportedFrameRates`, and `XRSession.updateTargetFrameRate`
Fixes #237
> Surface framerate info/functionality

- webxr-api/frame.rs
- webxr/glwindow/mod.rs
- webxr/headless/mod.rs
- webxr/openxr/mod.rs
This adds a `predicted_display_time` to the Frame object, corresponding to `XRFrame.predictedDisplayTime`. Currently only OpenXR surfaces a real value for this, so the headless and GLWindow backends just report 0 for now.
> Surface predicted display time on Frame object

- webxr/openxr/graphics.rs
- webxr/openxr/graphics_d3d11.rs
- webxr/openxr/input.rs
- webxr/openxr/mod.rs
This removes the explicit dependency on D3D11 in the OpenXR code and should hopefully lay the groundwork for future support on other platforms like Linux or Android.
> OpenXR: Separate graphics handling from main OpenXR code

- webxr-api/device.rs
- webxr-api/mock.rs
- webxr-api/session.rs
- webxr/headless/mod.rs
- webxr/openxr/mod.rs
In my initial implementation I represented reference space bounds with a Box2D, as those extents are what OpenXR returns. However, the bounds geometry can technically be an arbitrary length, and the WPT tests do in fact test for this. This changes the bounds geometry to be represented as a Vec of Point2Ds instead, as well as adding support for updating bounds geometry in the mock device.
> Update bounded space handling, add support in mock

- webxr/openxr/graphics_d3d11.rs
- webxr/openxr/mod.rs
This PR allows for OpenXR sessions to function properly with SteamVR as well as Oculus. It adds `DXGI_FORMAT_B8G8R8A8_UNORM_SRGB` to `pick_format` for D3D11, as SteamVR does not take `DXGI_FORMAT_B8G8R8A8_UNORM`. There doesn't appear to be any noticable performance hit from gamma correction, and indeed it actually displays colors in the session more accurately than Oculus runtime, which is not running gamma correction currently. It also adjusts the manipulation of views, as it turns out that just flipping the up/down angles on the FOVs during composition layer submission is no longer sufficient. It seems that as long as windows sessions are solely backed by D3D11, we'll need to apply the same inverted view + reversed winding fix for SteamVR as well as Oculus.
Fixes #217
> Support SteamVR-backed sessions for OpenXR

- webxr-api/lib.rs
- webxr-api/mock.rs
- webxr/headless/mod.rs
Adds new MockInputMsgs related to setSupportedButtons and updateButtonState from the WebXR Test API.
> mock: Add infra for supported buttons

- webxr-api/events.rs
- webxr-api/mock.rs
- webxr-api/space.rs
- webxr/headless/mod.rs
- webxr/openxr/mod.rs
This adds support for reference space change events for OpenXR and mock backends.
> Add support for reference space change events

- .github/workflows/rust.yml
- webxr-api/layer.rs
- webxr/Cargo.toml
- webxr/gl_utils.rs
- webxr/glwindow/mod.rs
- webxr/openxr/mod.rs
- webxr/surfman_layer_manager.rs
[sparkle](https://github.com/servo/sparkle) is servo owned (but mostly unmaintained) gl create that we would like to archive and replace with [glow](https://github.com/grovesNL/glow/tree/main), that is actively maintained and used by wgpu and wider rust community.
Part of https://github.com/servo/servo/issues/33539
> Use glow instead of sparkle

- webxr/Cargo.toml
- webxr/glwindow/mod.rs
This PR update glwindow port to use the same winit window. And since it creates new surfman context entirely, we could just create discovery type without requiring surfman types.
> Create surfman context from scratch in glwindow
